# Generated by Django 2.2.9 on 2020-03-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
