# Generated by Django 4.1.4 on 2022-12-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
    ]
