# Generated by Django 4.1.4 on 2022-12-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
