# Generated by Django 4.1.4 on 2023-01-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_formation_group_delete_eventpage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="formation_group",
            new_name="host_formation",
        ),
    ]
