# Generated by Django 3.0.5 on 2020-04-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0007_auto_20200412_1841"),
        ("events", "0004_auto_20200413_0059"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="formation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="committees.Committee",
            ),
        ),
    ]
