# Generated by Django 4.1.4 on 2023-01-03 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0052_alter_committeepage_options"),
        ("events", "0004_alter_event_formation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="formation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="committees.committeepage",
            ),
        ),
    ]
