# Generated by Django 4.1.4 on 2023-01-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_rename_formation_group_event_host_formation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
