# Generated by Django 4.1.4 on 2023-01-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_formation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="formation",
            new_name="formation_group",
        ),
    ]
