# Generated by Django 4.1.4 on 2023-01-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_id_alter_event_uuid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventsPage",
        ),
    ]
