# Generated by Django 3.0.5 on 2020-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200413_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actionnetwork_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
