# Generated by Django 3.0.5 on 2020-04-13 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_actionnetwork_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(1, 1, 1, 1, 1, 1))),
            ],
        ),
    ]
