# Generated by Django 3.0.5 on 2020-04-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0014_auto_20200418_1749"),
        ("events", "0008_apicalls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="formation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="committees.CommitteePage",
            ),
        ),
    ]
