# Generated by Django 3.1.8 on 2021-04-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20210414_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='actionnetwork_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='actionnetwork_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
