# Generated by Django 3.2.6 on 2021-08-22 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20210414_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicalls',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
