# Generated by Django 3.2.6 on 2021-08-31 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0032_remove_committeepage_name'),
        ('events', '0019_eventspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='committees.committee'),
        ),
    ]
