# Generated by Django 4.1.4 on 2022-12-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
