# Generated by Django 4.1.4 on 2022-12-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0051_alter_resourcespage_resources"),
        ("events", "0024_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="formation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="committees.committeepage",
            ),
        ),
    ]
