# Generated by Django 4.1.4 on 2022-12-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_alter_event_formation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
