# Generated by Django 4.1.4 on 2022-12-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_alter_event_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-start"]},
        ),
    ]
