# Generated by Django 4.1.4 on 2022-12-31 01:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_alter_event_options_alter_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
