# Generated by Django 4.1.4 on 2022-12-31 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_alter_event_options_alter_event_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="id",
            new_name="uuid",
        ),
    ]
