# Generated by Django 3.0.4 on 2020-03-26 03:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_blogpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='NewsPage',
        ),
    ]
