# Generated by Django 3.0.4 on 2020-03-26 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200325_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='intro',
        ),
    ]
