# Generated by Django 3.0.5 on 2020-05-12 02:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_infopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='additional_content',
            field=wagtail.core.fields.StreamField([('embed', wagtail.core.blocks.RawHTMLBlock())], null=True),
        ),
    ]
