# Generated by Django 3.1.8 on 2021-04-13 00:35

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_auto_20210412_1827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "header",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "header",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("h1", "H1"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                            ("h5", "H5"),
                                            ("h6", "H6"),
                                        ],
                                        label="Header Size",
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Text", max_length=50
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("text", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "subsection",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "header",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "header",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("h1", "H1"),
                                                        ("h2", "H2"),
                                                        ("h3", "H3"),
                                                        ("h4", "H4"),
                                                        ("h5", "H5"),
                                                        ("h6", "H6"),
                                                    ],
                                                    label="Header Size",
                                                ),
                                            ),
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text", max_length=50
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                ("text", wagtail.blocks.TextBlock()),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
