# Generated by Django 3.1.8 on 2021-04-13 04:04

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_auto_20210412_2254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StreamBlock(
                            [
                                ("header", wagtail.blocks.CharBlock()),
                                ("text", wagtail.blocks.RichTextBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("quote", wagtail.blocks.BlockQuoteBlock()),
                                (
                                    "subsection",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            ("header", wagtail.blocks.CharBlock()),
                                            ("text", wagtail.blocks.TextBlock()),
                                            (
                                                "subsubsection",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "header",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.TextBlock(),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
