# Generated by Django 3.2.14 on 2022-07-07 02:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('news', '0015_auto_20210412_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='body',
            new_name='main_story_copy',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='date',
        ),
        migrations.AddField(
            model_name='newspage',
            name='action_network_href',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newspage',
            name='main_story_heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newspage',
            name='main_story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='related_stories',
            field=wagtail.fields.StreamField([('related_story', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('copy', wagtail.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='body',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('subsection', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock()), ('subsubsection', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock())]))]))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='additional_content',
            field=wagtail.fields.StreamField([('embed', wagtail.blocks.RawHTMLBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
