# Generated by Django 3.2.13 on 2022-06-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20220621_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspagerelatedstories',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newspagerelatedstories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newspagerelatedstories',
            name='link_external',
            field=models.URLField(blank=True, null=True, verbose_name='External link'),
        ),
        migrations.AddField(
            model_name='newspagerelatedstories',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
