# Generated by Django 3.2.13 on 2022-06-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20220621_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='date',
            field=models.DateTimeField(verbose_name='Schedule Send Date + Time'),
        ),
    ]
