# Generated by Django 3.2.16 on 2022-10-11 05:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('news', '0017_alter_newspage_related_stories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsIndexPage',
            new_name='NewsletterIndexPage',
        ),
        migrations.RenameModel(
            old_name='NewsPage',
            new_name='NewsletterPage',
        ),
    ]
