# Generated by Django 3.2.13 on 2022-07-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_newspage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='date',
        ),
    ]
