# Generated by Django 3.2.16 on 2022-10-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20221011_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterpage',
            name='subject',
            field=models.CharField(default='', max_length=255, verbose_name='Email Subject'),
            preserve_default=False,
        ),
    ]
