# Generated by Django 3.2.13 on 2022-07-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_remove_newspage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='schedule_send_href',
            field=models.URLField(blank=True, null=True),
        ),
    ]
