# Generated by Django 3.2.13 on 2022-07-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_newspage_schedule_send_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='schedule_send_href',
            new_name='action_network_href',
        ),
    ]
