# Generated by Django 4.1.4 on 2022-12-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0021_alter_newspage_stories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newspage",
            old_name="main_story_image",
            new_name="banner_image",
        ),
    ]
