# Generated by Django 3.2.13 on 2022-07-02 07:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_rename_schedule_send_href_newspage_action_network_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='related_stories',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, use_json_field=None),
        ),
        migrations.DeleteModel(
            name='NewsPageRelatedStories',
        ),
    ]
