# Generated by Django 4.1.4 on 2022-12-13 02:54

from django.db import migrations
import news.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0024_alter_newspage_stories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="stories",
            field=wagtail.fields.StreamField(
                [("related_story", wagtail.blocks.StreamBlock([]))],
                blank=True,
                default=news.models.upcoming_events_as_related_stories,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
