# Generated by Django 4.1.4 on 2022-12-13 02:56

from django.db import migrations
import news.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0025_alter_newspage_stories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="stories",
            field=wagtail.fields.StreamField(
                [("related_story", wagtail.blocks.RichTextBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
