# Generated by Django 4.1.4 on 2022-12-30 13:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0028_story_remove_newspage_stories_newspagerelatedstories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="copy",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
