# Generated by Django 4.1.4 on 2022-12-30 13:19

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0031_alter_story_copy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="copy",
        ),
        migrations.AddField(
            model_name="story",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
