# Generated by Django 3.2.13 on 2022-07-03 07:07

from django.db import migrations
import news.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_alter_newspage_related_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='body',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('subsection', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock()), ('subsubsection', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock())]))]))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='additional_content',
            field=wagtail.fields.StreamField([('embed', wagtail.blocks.RawHTMLBlock())], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='related_stories',
            field=wagtail.fields.StreamField([('related_story', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, default=news.models.upcoming_events_as_related_stories, null=True, use_json_field=True),
        ),
    ]
