# Generated by Django 3.2.13 on 2022-07-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_auto_20220703_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='body',
            new_name='main_story_copy',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='heading',
            new_name='main_story_header',
        ),
        migrations.AddField(
            model_name='newspage',
            name='main_story_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
