# Generated by Django 3.2.13 on 2022-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_auto_20220703_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='main_story_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
