# Generated by Django 4.1.4 on 2022-12-31 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0051_alter_resourcespage_resources"),
        ("news", "0046_alter_newspage_main_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="formation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="committees.committeepage",
            ),
        ),
    ]
