# Generated by Django 4.1.4 on 2022-12-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0046_alter_newspage_main_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsPageRelatedStories",
        ),
    ]
