# Generated by Django 3.2.13 on 2022-07-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('news', '0047_alter_newspage_main_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='main_story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
