# Generated by Django 4.1.4 on 2022-12-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0047_newspage_formation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newspage",
            old_name="banner_image",
            new_name="featured_image",
        ),
    ]
