# Generated by Django 4.1.4 on 2022-12-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0048_rename_banner_image_newspage_featured_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newspage",
            old_name="main_copy",
            new_name="description",
        ),
    ]
