# Generated by Django 3.2.14 on 2022-07-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0050_rename_main_story_heading_newspage_main_story_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='main_story_header',
            new_name='main_story_heading',
        ),
    ]
