# Generated by Django 3.2.14 on 2022-07-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0051_rename_main_story_header_newspage_main_story_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='related_stories',
        ),
    ]
