# Generated by Django 4.1.4 on 2023-01-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0052_alter_newspagerelatedstory_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsindexpage",
            options={"verbose_name": "Updates"},
        ),
        migrations.AlterModelOptions(
            name="newspage",
            options={"verbose_name": "Update"},
        ),
        migrations.RemoveField(
            model_name="newspage",
            name="formation",
        ),
    ]
