# Generated by Django 3.2.14 on 2022-07-06 18:40

from django.db import migrations
import news.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0053_newspage_related_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='body',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('subsection', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock()), ('subsubsection', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock())]))]))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='related_stories',
            field=wagtail.fields.StreamField([('related_story', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('copy', wagtail.blocks.TextBlock())]))], blank=True, default=news.models.upcoming_events_as_related_stories, null=True, use_json_field=True),
        ),
    ]
