# Generated by Django 3.2.14 on 2022-07-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0054_auto_20220706_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='related_stories',
        ),
    ]
