# Generated by Django 4.1.4 on 2023-01-03 10:53

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0057_newspagerelatedstory_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspagerelatedstory",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
