# Generated by Django 3.2.14 on 2022-07-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0059_alter_newspage_related_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='related_stories',
        ),
    ]
