# Generated by Django 3.2.14 on 2022-07-07 02:21

from django.db import migrations
import news.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0067_alter_newspage_related_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='body',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('subsection', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock()), ('subsubsection', wagtail.blocks.StreamBlock([('header', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock())]))]))]))], blank=True, use_json_field=False),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='additional_content',
            field=wagtail.fields.StreamField([('embed', wagtail.blocks.RawHTMLBlock())], blank=True, null=True, use_json_field=False),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='related_stories',
            field=wagtail.fields.StreamField([('related_story', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('copy', wagtail.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, default=news.models.upcoming_events_as_related_stories, null=True, use_json_field=False),
        ),
    ]
