# Generated by Django 4.1.4 on 2023-01-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_alter_officers_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officers",
            name="person",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
