# Generated by Django 4.1.7 on 2023-02-16 08:17

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0008_rename_article_name_bylawarticle_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bylawarticle",
            name="body",
            field=wagtail.fields.RichTextField(),
        ),
    ]
