# Generated by Django 4.2.7 on 2023-11-14 04:33

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0009_alter_bylawarticle_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executivecommitteepage",
            name="description",
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
