# Generated by Django 3.0.5 on 2020-05-12 03:06

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_infopage_additional_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infopage",
            name="additional_content",
            field=wagtail.fields.StreamField(
                [("embed", wagtail.blocks.RawHTMLBlock())], blank=True, null=True
            ),
        ),
    ]
