# Generated by Django 3.1.2 on 2020-10-22 04:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0052_pagelogentry"),
        ("news", "0008_auto_20200511_2206"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "document",
                    wagtail.fields.StreamField(
                        [
                            (
                                "h1",
                                wagtail.blocks.StreamBlock(
                                    [("h2", wagtail.blocks.TextBlock())]
                                ),
                            ),
                            ("text", wagtail.blocks.TextBlock()),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
