# Generated by Django 3.1.6 on 2021-02-04 06:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_documentpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentpage",
            name="document",
            field=wagtail.fields.StreamField(
                [
                    (
                        "h1",
                        wagtail.blocks.StreamBlock(
                            [("h2", wagtail.blocks.TextBlock())]
                        ),
                    ),
                    ("p", wagtail.blocks.TextBlock()),
                ]
            ),
        ),
    ]
