# Generated by Django 4.1.4 on 2022-12-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0034_story_committee"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="main_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_event",
                to="events.event",
            ),
        ),
    ]
