# Generated by Django 4.1.4 on 2023-01-03 10:05

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0054_remove_newspage_related_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="featured_image",
        ),
        migrations.AlterField(
            model_name="newspagerelatedstory",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="news.newspage",
            ),
        ),
    ]
