# Generated by Django 4.1.4 on 2023-01-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0055_remove_newspage_featured_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspagerelatedstory",
            name="image",
        ),
    ]
