# Generated by Django 4.1.4 on 2023-01-03 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_delete_eventspage"),
        ("news", "0058_alter_newspagerelatedstory_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspagerelatedstory",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_event",
                to="events.event",
            ),
        ),
    ]
