# Generated by Django 4.1.4 on 2023-01-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0059_alter_newspagerelatedstory_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newspagerelatedstory",
            old_name="event",
            new_name="related_event",
        ),
    ]
