# Generated by Django 4.1.4 on 2023-01-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("news", "0060_rename_event_newspagerelatedstory_related_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspagerelatedstory",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
