# Generated by Django 4.1.4 on 2023-01-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0061_newspagerelatedstory_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newspagerelatedstory",
            old_name="image",
            new_name="related_image",
        ),
    ]
