# Generated by Django 4.1.7 on 2023-04-04 10:30

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0064_newspagerelatedstory_sponsoring_formation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Avoid unnecessary copy such as 'RSVP Here' if attached to an event.",
            ),
        ),
    ]
