# Generated by Django 4.1.7 on 2023-04-04 11:15

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0065_alter_newspage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="newspagerelatedstory",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Avoid unnecessary copy such as 'RSVP Here' if attached to an event.",
                null=True,
            ),
        ),
    ]
