# Generated by Django 4.2.6 on 2023-10-09 11:04

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0067_newspage_featured_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="introduction",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
