# Generated by Django 4.1.4 on 2022-12-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_highlighted_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="banner_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="mission_statement",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="values_statement",
        ),
    ]
