# Generated by Django 3.0.5 on 2020-04-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0007_auto_20200412_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
