# Generated by Django 3.0.5 on 2020-04-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0016_auto_20200418_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeepage',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
