# Generated by Django 3.1.2 on 2020-10-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0020_auto_20201017_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeepage',
            name='api_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
