# Generated by Django 3.2.6 on 2021-09-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0035_committeepage_leader_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeespage',
            name='repeat_in_subnav',
            field=models.BooleanField(default=False, help_text="If checked, a link to this page will be repeated alongside it's direct children when displaying a sub-navigation for this page.", verbose_name='repeat in sub-navigation'),
        ),
        migrations.AddField(
            model_name='committeespage',
            name='repeated_item_text',
            field=models.CharField(blank=True, help_text="e.g. 'Section home' or 'Overview'. If left blank, the page title will be used.", max_length=255, verbose_name='repeated item link text'),
        ),
    ]
