# Generated by Django 3.2.10 on 2022-01-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0043_remove_person_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='uuid',
        ),
    ]
