# Generated by Django 5.0 on 2023-12-17 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("committees", "0061_committeepage_gcal_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="committeepage",
            name="email",
        ),
    ]
