# Generated by Django 5.0 on 2023-12-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("committees", "0064_delete_committeespage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeepage",
            name="formation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CT", "Committee"),
                    ("WG", "Working Group"),
                    ("CU", "Caucus"),
                ],
                default="",
                max_length=2,
                null=True,
            ),
        ),
    ]
