# Generated by Django 2.2.9 on 2020-03-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='profile',
            new_name='user',
        ),
    ]
