# Generated by Django 3.0.5 on 2020-04-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='shortname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
