# Generated by Django 3.0.5 on 2020-04-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_auto_20200412_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
