# Generated by Django 3.0.5 on 2020-04-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_auto_20200412_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='shortname',
            new_name='slug',
        ),
    ]
