# Generated by Django 3.0.5 on 2020-04-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_auto_20200412_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='formation_type',
            field=models.CharField(choices=[('C', 'Committee'), ('WG', 'Working Group')], max_length=2, null=True),
        ),
    ]
