# Generated by Django 3.0.5 on 2020-04-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0006_committee_formation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='formation_type',
            field=models.CharField(choices=[('C', 'Committee'), ('WG', 'Working Group')], default='', max_length=2),
        ),
    ]
