# Generated by Django 3.0.5 on 2020-04-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('committees', '0010_auto_20200418_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='slug',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='CommitteePage',
        ),
    ]
