# Generated by Django 3.0.5 on 2020-04-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200418_1749'),
        ('committees', '0014_auto_20200418_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
