# Generated by Django 3.0.5 on 2020-04-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0015_delete_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
