# Generated by Django 3.1.2 on 2020-10-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0018_auto_20200418_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeepage',
            name='api_key',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committeepage',
            name='formation_type',
            field=models.CharField(choices=[('CT', 'Committee'), ('WG', 'Working Group'), ('CU', 'Caucus'), ('PR', 'Priority')], default='', max_length=2),
        ),
    ]
