# Generated by Django 3.1.2 on 2020-10-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0019_auto_20201015_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeepage',
            name='api_key',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
