# Generated by Django 3.1.2 on 2020-10-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0022_committeepage_sign_up_embed_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeepage',
            old_name='sign_up_embed_code',
            new_name='sign_up_form_endpoint',
        ),
    ]
