# Generated by Django 3.1.8 on 2021-04-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0023_auto_20201019_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
