# Generated by Django 3.1.8 on 2021-08-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0024_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeepage',
            name='leader_name',
        ),
    ]
