# Generated by Django 3.1.8 on 2021-08-09 08:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("committees", "0026_person_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourcesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "resources",
                    wagtail.fields.StreamField(
                        [
                            ("resource", wagtail.blocks.CharBlock()),
                            ("information", wagtail.blocks.RichTextBlock()),
                            (
                                "structured_info",
                                wagtail.blocks.StreamBlock(
                                    [
                                        ("heading", wagtail.blocks.CharBlock()),
                                        ("body", wagtail.blocks.RichTextBlock()),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
