# Generated by Django 3.1.8 on 2021-08-09 08:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0027_resourcespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcespage',
            name='resources',
            field=wagtail.fields.StreamField([('name', wagtail.blocks.CharBlock()), ('information', wagtail.blocks.RichTextBlock()), ('structured_info_block', wagtail.blocks.StreamBlock([('heading', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.RichTextBlock())]))]),
        ),
    ]
