# Generated by Django 3.2.6 on 2021-08-22 02:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0028_auto_20210809_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcespage',
            name='resources',
            field=wagtail.core.fields.StreamField([('resource', wagtail.core.blocks.StreamBlock([('resource_name', wagtail.core.blocks.CharBlock()), ('information', wagtail.core.blocks.RichTextBlock()), ('structured_info_block', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.RichTextBlock())]))]))]),
        ),
    ]
