# Generated by Django 3.2.6 on 2021-08-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0029_alter_resourcespage_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
