# Generated by Django 3.2.6 on 2021-08-31 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_formation'),
        ('committees', '0032_remove_committeepage_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
