# Generated by Django 3.2.6 on 2021-08-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0033_delete_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeepage',
            name='api_key',
        ),
    ]
