# Generated by Django 3.2.10 on 2022-01-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0036_auto_20210903_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='membership',
            field=models.BooleanField(null=True),
        ),
    ]
