# Generated by Django 3.2.10 on 2022-01-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0037_alter_person_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tags',
        ),
    ]
