# Generated by Django 3.2.10 on 2022-01-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0039_person_taggings_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='taggings_href',
            field=models.URLField(default='https://None'),
            preserve_default=False,
        ),
    ]
