# Generated by Django 3.2.10 on 2022-01-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0041_remove_person_taggings_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
