# Generated by Django 3.2.10 on 2022-01-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0042_person_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='membership',
        ),
    ]
