# Generated by Django 3.2.11 on 2022-01-11 05:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0044_auto_20220109_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeespage',
            name='description',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
