# Generated by Django 3.2.13 on 2022-07-03 07:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0048_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcespage',
            name='resources',
            field=wagtail.fields.StreamField([('resource', wagtail.blocks.StreamBlock([('resource_name', wagtail.blocks.CharBlock()), ('information', wagtail.blocks.RichTextBlock()), ('structured_info_block', wagtail.blocks.StreamBlock([('heading', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.RichTextBlock())]))]))], use_json_field=True),
        ),
    ]
