# Generated by Django 4.1.4 on 2023-01-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0051_alter_resourcespage_resources"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committeepage",
            options={"verbose_name": "Formation"},
        ),
    ]
