# Generated by Django 4.1.7 on 2023-04-04 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("committees", "0056_committeepage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="committeepage",
            name="leader_name",
        ),
        migrations.AddField(
            model_name="committeepage",
            name="leaders",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
