# Generated by Django 4.1.8 on 2023-05-25 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("committees", "0059_alter_committeepage_leaders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeepage",
            name="leaders",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
