# Generated by Django 5.0 on 2023-12-17 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("committees", "0063_remove_committeepage_leader_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommitteesPage",
        ),
    ]
