# Generated by Django 5.0.1 on 2024-01-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("committees", "0065_alter_committeepage_formation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
