# Generated by Django 5.1.2 on 2024-10-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0065_alter_committeepage_formation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeepage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
