# Generated by Django 5.0.1 on 2024-01-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("committees", "0066_formation"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
