version: "3.8"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
    
    environment:
      - DJANGO_SECRET_KEY=asdf
    network_mode: service:db
 
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  
  cypress:
    image: cypress/included


volumes:
  postgres-data:
