# Generated by Django 3.2.6 on 2021-08-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210825_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='action_network_embed_api_endpoint',
            field=models.URLField(blank=True, null=True),
        ),
    ]
