# Generated by Django 4.1.4 on 2023-01-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_homepage_banner_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="call_to_action",
            field=models.URLField(blank=True, null=True),
        ),
    ]
