# Generated by Django 3.1.8 on 2021-08-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210809_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership',
        ),
    ]
