# Generated by Django 4.1.4 on 2023-01-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0005_alter_officers_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officers",
            name="position",
            field=models.IntegerField(
                choices=[
                    (
                        1,
                        "Co Chairs Treasurer Corresponding Secretary Recording Secretary Comrades At Large",
                    )
                ]
            ),
        ),
    ]
