# Generated by Django 4.1.5 on 2023-02-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0007_bylawspage_bylawarticle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bylawarticle",
            old_name="article_name",
            new_name="name",
        ),
    ]
