# Generated by Django 4.2.7 on 2023-11-14 04:39

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0012_alter_bylawarticle_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bylawspage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
