name: Devcontainer Build

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Devcontainer Build
        uses: devcontainers/ci@v0.3
